name: "Reviewer lottery"

on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]
  workflow_dispatch: # for test
    inputs:
      is_test:
        description: 'Is this a test run?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: uesteibar/reviewer-lottery@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
            
