name: "Study review"

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch: # for test
    inputs:
      is_test:
        description: 'Is this a test run?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  pick-random-reviewer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: study-review
      id: study-review
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          const team = ["griiim134", "Kim JinWoo", "Noong2", "workminkyoung", "Yujin Park"];
          const candidateList = team.filter((e) => e != "${{ github.event.pull_request.user.login }}");
          const reviewer = candidateList[Math.floor(Math.random() * candidateList.length)];
          const comment = "@${reviewer}님. 리뷰 부탁드립니다!";
          core.setOutput("comment", comment)
          core.setOutput("reviewer", reviewer);

    - name: Add Comment
      uses: mshick/add-pr-comment@v2
      with:
          repo-token: ${{ secrets.TOKEN }}
          message: |
            ${{ steps.study-review.outputs.comment }}

    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.TOKEN }}
        reviewers: ${{ steps.study-review.outputs.reviewer }}
